### ISSUE TITLE
ACE medical and Arma revive (respawning system) are conflicting

### ISSUE THREAD

**Issue by foofski** [jabberzac/Overthrow#17]
A player can appear within ACE medical as being healed, but remain incapacitated waiting for a vanilla Arma revive. The player can use ace medical actions on themselves while in this state.

Players get the standard Arma "hold space to respawn" prompt, but other players do not get a revive action menu option.

**Comment by armazac** [comment]
Similar issues with ACE repair

**Comment by armazac** [comment]
![image](https://cloud.githubusercontent.com/assets/19246239/19630044/16c47f3c-99ce-11e6-9532-175361f45186.png)
woops....
