### ISSUE TITLE
Sometimes you cannot connect to a purchased UAV

### ISSUE THREAD

**Issue by foofski** [jabberzac/Overthrow#38]
(From steam feedback; but I have had this too)

This may be an ACE permissions thing (i.e. need to be a UAV operator)?
Else Arma can be fussy with these at the best of times (e.g. faction mismatch terminal -> UAV)

**Comment by armazac** [comment]
Are you zooming into the ground in your UAV terminal where the UAV is and right clicking the UAV?

I have never had a problem with this, and I use a UAV for probably 20% of my time :P
