### ISSUE TITLE
Various items can be lost when using transfer option

### ISSUE THREAD

**Issue by armazac** [jabberzac/Overthrow#44]
lets just make this foolproof

**Comment by dephelis** [comment]
As of 0.5.6, weapon optics and vests are transferring but are rendered unusable. The items are missing their icon in the inventory view and can not be equipped.

When dropped on the ground their models appear normally.

**Comment by dephelis** [comment]
@armazac There are still issues with transferring in 0.5.6 (see comment above). Also behaviour described in #36 is still being exhibited during transfers.
