### ISSUE TITLE
Upon loading, objects that spawn inside the shack are strewn around

### ISSUE THREAD

**Issue by spectre1995** [jabberzac/Overthrow#51]
-Upon reloading persistent save in singleplayer, objects that spawn inside the shack are strewn around. The map usually spawns face down, or pushed against the door, and the desk/toolbox/gas can usually spawn underneath the shack, or somewhere outside of it.

-Shot down a NATO UAV and it counted as a civilian killed

-Occasionally, objects placed inside backpacks and loaded into a vehicle will disappear upon reloading a persistent save.

-Just loaded a persistent save for singleplayer, it did not put me back where I last saved (FOB), but instead placed me on the island with the intro. When I finally made my way back to the FOB, I could not reset the UI (it did not load) from the map.

**Comment by armazac** [comment]
Hi, please keep issues to one bug :)
