### ISSUE TITLE
[Q] Arma Enchanced Movement

### ISSUE THREAD

**Issue by Dexious** [jabberzac/Overthrow#56]
Hello,

I can't use the mod "Arma Enhanced Movement".

Sometimes if i die works.

Did you disable it on purpose or it's just a conflict?

Mods: CBA_A3, ACE, Arma Enhanced Movement

Tested: Dedicated Server

**Comment by armazac** [comment]
Hi we are not disabling it, and I use it myself with no issues

**Comment by TahMahn** [comment]
My apologies if I'm wrong, but Enhanced Movement is a bit wonky with every mod. Sometimes it works, sometimes it doesn't. (I think that's because the engine ArmA runs on wasn't designed for that kind of movement.)
