### ISSUE TITLE
Beginning Issue #1

### ISSUE THREAD

**Issue by TheAngryPacifist** [jabberzac/Overthrow#59]
I saw that you wanted us to keep our issues separated. However these may be related to each other. 

We have a large group of people. When I tried to restart the server, the beginning title screen does not show up for me. It shows the beach and fully loads in, however nothing shows up for the option of "new game" or "Load Persistent"

**Comment by justinwho** [comment]
as before you have to be in host slot to start the game if your friends are in that slot they get the msg
