### ISSUE TITLE
Beginning issue #2

### ISSUE THREAD

**Issue by TheAngryPacifist** [jabberzac/Overthrow#60]
The second issue is that I hosted a server for around 5 people at once, and the server gave the main menu to my roommate instead of me.

**Comment by justinwho** [comment]
my friend and i had this problem you have to be in host spot for now to get the popup

**Comment by Richshade** [comment]
Join the discord server, and it might be in the comments section of the mod page (on steam), but the host has to be in the number three slot if I remember correctly and has not been renamed, but it sound likes it has. Also Issue #1 and #2 are the same as far as the description goes
