### ISSUE TITLE
Beginning issue #3

### ISSUE THREAD

**Issue by TheAngryPacifist** [jabberzac/Overthrow#61]
The last issue we had was some of the players spawn onto the island where the beach is. The were unable to respawn, and when committing suicide (drowning), they would respawn onto the island. We were never able to have him join us.

We are a large group of players who love your mod and are currently playing on it a lot, and would be happy to help in any way possible.

**Comment by justinwho** [comment]
the time limit on moving people is random or you get teleported but still on the island

my friend and i had this issue we restarted the game and the server and seem to fix it but might be a bug

**Comment by Richshade** [comment]
I may suggest, I have not had more than four people play at once and only had two people load in at the same time so maybe space out your friends so one is joining at a time and you might have to start a new game. Saying that, if they can use the Y menu, have somebody on the main land (Starter island) place a camp and then have them fast travel. Let them take loot from the first few bodies, get about $400-$500 and then have them by a shack and make sure they click set home just in case. Hope that helped

**Comment by TheAngryPacifist** [comment]
The problem is still consistent even with 2 people

**Comment by foofski** [comment]
There are still some occasional issues with house assignment on spawn (e.g. doubling up / can't find) - this is being worked on.
