### ISSUE TITLE
Persistent Save Loading Not Working (MP)

### ISSUE THREAD

**Issue by TyroneBiggins** [jabberzac/Overthrow#63]
Tried the persistent save load several times on my locally hosted server.    It saves perfectly fine.   I exit  the server and follow the instructions on the wiki.  Upon clicking "Restart"  and loading it up, I choose the "Host" slot and begin the scenario.  When i get the options to select new game or load game, I click the load game.  It then says "loading ....please wait....." for several minutes and then the text disappears and I am stuck on the beach scene.  I waited a little longer just in case it was taking a while, but it seems to be stuck in a loop and doesnt move from that beach scene.      As of now, I am resorting to using the Arma save/load function and just resetting the UI with the map.

**Comment by armazac** [comment]
You will need to provide a .rpt file or simply start a new game, your save could be corrupt.
