### ISSUE TITLE
Certain players cannot see missions, while other can, missions activated.

### ISSUE THREAD

**Issue by TheAngryPacifist** [jabberzac/Overthrow#75]
When we are playing, a mission will appear and people are unable to see them, while other can. When the people who can't re-log the game, they can see it perfectly fine. The problem is I am the host and I cannot re-log the game.

**Comment by TyroneBiggins** [comment]
I second this.  Sometimes i cannot see any missions or tasks appearing except for the main Battle for X missions.  I cant see any gang leader location pop ups either.

**Comment by foofski** [comment]
Old Version
