### ISSUE TITLE
Units stuck frozen running in place

### ISSUE THREAD

**Issue by TyroneBiggins** [jabberzac/Overthrow#76]
After playing for awhile and buying several buildings and capturing 2 towns, I noticed at times units both enemy and civilian will run and walk in place like they are frozen.  It is almost like the server is lagged up or something, but my character can run around and equip items, drive vehicles, and fast travel just fine.  The clearing body command won't work when this is occurring.  And several times Ive had to restart the dedicated server to fix this.  One time it even corrupted a save file.  Not sure whats causing it, but it seems like the AI itself is the thing thats lagging, as its only lag from the units.

**Comment by TyroneBiggins** [comment]
I should add, this only occurs after playing for a while.   On a fresh start, it doesnt occur until around day 3 or 4 when there has been progress made, and players own vehicles and houses, etc.

**Comment by TyroneBiggins** [comment]
I found out the bug seems to be when I fast travel too fast.   If i die and want to get back into the action, i spawn at house and immediately try and fast travel away to my death location.  The problem is that in my home area I have 10 hired police officers + civilians running around.  Im guessing they are in the middle of spawning and then I end the process by fast traveling to a new location which messes it up.

**Comment by foofski** [comment]
Old version
