### ISSUE TITLE
not strat

### ISSUE THREAD

**Issue by l3al3akshafiei** [jabberzac/Overthrow#80]
After click new game  15 minute later only show beach please help need for single player only work version 6.9 
6.9.1 6.9.2 and 7.0.0 not worked please help

**Comment by foofski** [comment]
Come and chat with us in Discord if you still have this issue.

**Comment by l3al3akshafiei** [comment]
dear need Discord ID

**Comment by foofski** [comment]
Hi,

Discord link: https://discord.gg/n8c3v

Kind Regards,

Foofski
