### ISSUE TITLE
Recruiting squads error

### ISSUE THREAD

**Issue by Adr316** [jabberzac/Overthrow#91]
For some reason me and a friend can not build recruits.  We have a barracks at one of the airfields we taken. we have a warehouse and all the funds needed but the units dont spawn when we build...

**Comment by foofski** [comment]
Please upload server logs (RPT) to pastebin.com and post a link here.

Instructions for finding these files are on the wiki.

**Comment by foofski** [comment]
Support request, Dealing with in Discord chat
